### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by jyli559** [hkust-zhiyao/MasterRTL#1]
Hello! I find a path in script like "/data/wenjifang/AST_analyzer/std_PPA.json" in graph_stat.py. It seems some problem rise if i dont have this file. How can I do?

**Comment by jyli559** [comment]
And we I run python3 clean_vlg.py I also get **No such file or directory**

**Comment by fangwenji** [comment]
Hi! Thanks for your feedback. I've updated the repo to fix the path issue and the clean_vlg.py file. Please feel free to contact me if you have any other questions!

**Comment by jyli559** [comment]
Hello, when I got to this 
## Power
$ cd preproc/power
$ python3 tr_propagate.py
, the command "file not found" came up again : No such file or directory: './design_hier.json'
and I realized that the file was indeed there, so what should I do?
This also occurs in  the  following
## Timing
$ cd feature_extract/timing
$ python3 feature_extra_graph_STA.py
I got : No such file or directory: '../../example/timing_dag/node_dict_update/TinyRocket_sog_node_dict_init.pkl'
