### ISSUE TITLE
Please provide the pre-train ML model or the method to train such a model

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#10]

**Comment by Lucas-Wye** [comment]
any update?

**Comment by fangwenji** [comment]
Hi, recently we have been focusing on improving the original version of MasterRTL, especially for the ML model part. The updated version will offer more coarse-grained and accurate predictions for timing, and will be much easier to implement. We intend to make our code openly accessible in the near future. If you are interested in our work, we may have some more detailed discussions through email.
