### ISSUE TITLE
how can this design apply to some other RTL design?

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#11]
could you write a script to help for customized HDL design?

**Comment by fangwenji** [comment]
The pre-processing part using Yosys are able to deal with most kinds of customized HDL designs. Please refer to the yosys script in https://github.com/hkust-zhiyao/MasterRTL/blob/main/ys_script/run_TinyRocket_sog.ys

**Comment by Lucas-Wye** [comment]
I mean a script to deal with all, rather than only one part. With that script, we can run the full flow automatically.

**Comment by fangwenji** [comment]
Please refer to #10

**Comment by xiaomi-xifan** [comment]
hello,can I ask you some question about this issue?

**Comment by fangwenji** [comment]
Sure, please feel free to email me about this work, here is my email address: wfang838@connect.ust.hk

**Comment by xiaomi-xifan** [comment]
> 当然，欢迎随时给我发邮件，这是我的邮箱地址：[wfang838@connect.ust.hk](mailto:wfang838@connect.ust.hk)
Hello, I sent you an email recently and hope you don’t mind me leaving another message. Could you please check it when you have time? I would like to ask about the relevant dataset. Thank you very much for your help!
