### ISSUE TITLE
Request for dataset 

### ISSUE THREAD

**Issue by luarss** [hkust-zhiyao/MasterRTL#3]
First of all, thanks for the great work in open-sourcing this interesting piece of work!

https://github.com/hkust-zhiyao/MasterRTL/blob/main/feature_extract/timing/train_path_rfr.py

I was wondering if there are any plans on releasing the datasets used to train the timing/area/power models needed for feature extraction?

**Comment by fangwenji** [comment]
Thank you for your interest in our work! 

All our datasets are collected from open-source benchmarks, I've updated the links of these benchmarks in the README file.
