### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './design_hier.json'

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#4]
refer to https://github.com/hkust-zhiyao/MasterRTL/issues/2

You have not uploaded the correct files, just the link files.

![image](https://github.com/hkust-zhiyao/MasterRTL/assets/30680577/329c0b3d-92ee-4d85-a1f5-cd576b8337d7)

**Comment by fangwenji** [comment]
Thank you so much for your interest in our work!
I've fixed the error of the soft link. The JSON file contains the hierarchy example of the TinyRocket design.
![image](https://github.com/hkust-zhiyao/MasterRTL/assets/44700913/1ac29fec-a242-46a9-a5a7-a69da989697f)

Please feel free to ask if you have any other questions.
