### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#5]
Traceback (most recent call last):
  File "MasterRTL/ML_model/timing/model/xgbooster_regression_kf_tns.py", line 1, in <module>
    from preprocess import *
  File "MasterRTL/ML_model/timing/model/preprocess.py", line 15, in <module>
    from utils.statistics import *
ModuleNotFoundError: No module named 'utils'

**Comment by fangwenji** [comment]
The utils file is only used for drawing the figures for our paper, and I've updated the code in the ML model folder by deleting the figure drawing part. Thank you so much for your feedback!

**Comment by Lucas-Wye** [comment]
sounds good.

BTW, could you privode the pre-trained model and give the python requirements for package and version?

Thx

**Comment by fangwenji** [comment]
[spec-list-qor.txt](https://github.com/hkust-zhiyao/MasterRTL/files/14627799/spec-list-qor.txt)
Here is the conda package we used for MasterRTL.
