### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/masterRTL/ML_model/data/label/dc_label_timing.json'

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#7]
Traceback (most recent call last):
  File "ML_model/timing/model/xgbooster_regression_kf_tns.py", line 62, in <module>
    label_data, feat_data = load_data()
  File "ML_model/timing/model/preprocess.py", line 22, in load_data
    with open(dc_label_data, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/masterRTL/ML_model/data/label/dc_label_timing.json'

**Comment by fangwenji** [comment]
The labels are collected after running logic synthesis using Design Compiler. You may replace the label files with your design benchmarks.
