### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/masterRTL/ML_model/data/label/dc_label_area_pwr.json'

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#8]
Traceback (most recent call last):
  File "ML_model/area/model/mix_regression_kf.py", line 117, in <module>
    label_data, feat_data = load_data_sep()
  File "ML_model/area/model/preprocess.py", line 46, in load_data_sep
    with open(dc_label_data, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/user/masterRTL/ML_model/data/label/dc_label_area_pwr.json'

**Comment by fangwenji** [comment]
The labels are collected after running logic synthesis using Design Compiler. You may replace the label files with your design benchmarks.

**Comment by Lucas-Wye** [comment]
> The labels are collected after running logic synthesis using Design Compiler. You may replace the label files with your design benchmarks.

thx, but how to generate such a label?

**Comment by fangwenji** [comment]
It depends on what types of constraints you need to use to generate the target ground-truth PPA. Due to the copyright issue, we could not share our logic synthesis flow using DC. However, you may build up your own flow according to the user manual.

**Comment by Lucas-Wye** [comment]
> It depends on what types of constraints you need to use to generate the target ground-truth PPA. Due to the copyright issue, we could not share our logic synthesis flow using DC. However, you may build up your own flow according to the user manual.

thx, I think I get you points. So the json file is consist of the design name and corresponding PPA, right?

**Comment by fangwenji** [comment]
Yes, that's correct.
