### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by Lucas-Wye** [hkust-zhiyao/MasterRTL#9]
Traceback (most recent call last):
  File "ML_model/power/model/mix_regression_kf.py", line 11, in <module>
    from utils.metrics import MAPE_one_val
ModuleNotFoundError: No module named 'utils'
Makefile:50: recipe for target 'run_ml_power' failed

**Comment by fangwenji** [comment]
Same problem as in #5
